version: '3.9'

services:
  backend:
    build: ./back_end
    container_name: livepatient-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/livepatient
    depends_on:
      - mongo

  frontend:
    build: ./front_end
    container_name: livepatient-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: livepatient-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
